disabled_rules:
- xctfail_message
- function_parameter_count
- legacy_constructor
- force_cast
- force_try
- identifier_name
- line_length
- multiple_closures_with_trailing_closure

type_body_length: 250
line_length: 120
function_body_length: 50
file_length: 500

excluded:
- Pods
